<template>
    <div>
        GolContainer
        <table cellspacing="1" cellpadding="0">
            <tr v-for="(row, i) in pixels" :key="i">
                <td v-for="(pixel, j) in row"
                    :key="j" :style="pixelStyle(pixel)"
                    @click="addCell(i,j)"></td>
            </tr>
        </table>
    </div>
</template>

<style lang="stylus" scoped>
td
    width 6px
    height 6px
    border none
    padding 0px
    margin 0px

tr
    font-size 6px
</style>

<script>


const vectorsToCheck = [[-1, -1], [-1, 0], [-1, 1],
    [0, -1], [0, 1], [1, -1], [1, 0], [1, 1]];

/**
 * Generate arrays with content generated by gen function.
 */
function makeArray(len, gen) {
    return Array.from(new Array(len), gen);
}

/**
 * Generate arrays with random content.
 */
function randomPixels(width, height) {
    return makeArray(height, () => (
        makeArray(width, () => Math.round(Math.random()))
    ));
}

function makeValidatorForRange(a, b) {
    return (n) => (n >= a && n <= b);
}

/**
 * Basic logic function saying if pixel should be turned on or off.
 */
function turnOnOrOff(i, j, oldPixels, height, width) {
    let aliveNeighbours = 0;

    const validXCoordinate = makeValidatorForRange(0, width - 1);
    const validYCoordinate = makeValidatorForRange(0, height - 1);

    const validCoordinates = ([x, y]) => (
        validXCoordinate(x) && validYCoordinate(y)
    );

    // vector way

    aliveNeighbours = vectorsToCheck
        // translate to point [j, i]
        .map(([x, y]) => ([x + j, y + i]))
        // filter out points out of bounds
        .filter(validCoordinates)
        // sum alive neighbours
        .reduce(
            (value, [x, y]) => (value + oldPixels[y][x]),
            0,
        );

    if (aliveNeighbours === 3) {
        return 1;
    }
    if (aliveNeighbours === 2 && oldPixels[i][j] === 1) {
        return 1;
    }

    return 0;
}

/**
 * Function to apply turnOnOrOff on every pixel, to transform old pixels
 * into newer version, in one time step.
 */
function evolve(pixels) {
    const oldPixels = pixels;

    const height = oldPixels.length;
    const width = oldPixels[0].length;

    const newPixels = oldPixels.map(
        (row, i) => row.map(
            (pixel, j) => turnOnOrOff(i, j, oldPixels, height, width),
        ),
    );

    return newPixels;
}

export default {

    data() {
        return {
            pixels: randomPixels(100, 100),
        };
    },

    mounted() {
        setInterval(() => this.stepForward(), 100);
    },

    methods: {
        pixelStyle(bit) {
            return `background-color: rgb(${255 * (1 - bit)},${255 * (1 - bit)},${255 * (1 - bit)})`;
        },

        stepForward() {
            this.pixels = evolve(this.pixels);
        },

        addCell(i, j) {
            this.pixels[i][j] = 1;
        },
    },
};
</script>
