import makeValidatorForRange from '../../helpers';

const vectorsToCheck = [[-1, -1], [-1, 0], [-1, 1],
    [0, -1], [0, 1], [1, -1], [1, 0], [1, 1]];

/**
 * Generate arrays with content generated by gen function.
 */
function makeArray(len, gen) {
    return Array.from(new Array(len), gen);
}

/**
 * Generate arrays with random content.
 */
function randomPixelsTricolor(width, height) {
    return makeArray(height, () => (
        makeArray(width, () => [
            Math.round(Math.random()),
            Math.round(Math.random()),
            Math.round(Math.random()),
        ])
    ));
}

/**
 * @param colorIdx color index
 */
function classicGoLTricolorRule(aliveNeighbours, oldPixels, i, j, colorIdx) {
    if (aliveNeighbours === 3) {
        return 1;
    }
    if (aliveNeighbours === 2 && oldPixels[i][j][colorIdx] === 1) {
        return 1;
    }

    return 0;
}

/**
 * Basic logic function saying if pixel colors should be turned on or off.
 * @param {integer} i y-index of central cell
 * @param {integer} j x-index of central cell
 * @param {Array} oldPixels Array of Arrays containing pixel color data as Array
 * with 3 elements, each for different color
 * @param {integer} height Maximal index for i, the height of GoL board
 * @param {integer} width Maximal index for j, the width of GoL board
 * @returns {Array} Array with 3 elements, each for different colour, each may
 * take value of 1 or 0
 */
function turnOnOrOffTricolor(i, j, oldPixels, height, width) {
    let aliveNeighboursByColor = [0, 0, 0];

    const validXCoordinate = makeValidatorForRange(0, width - 1);
    const validYCoordinate = makeValidatorForRange(0, height - 1);

    const validCoordinates = ([x, y]) => (
        validXCoordinate(x) && validYCoordinate(y)
    );

    // vector way

    aliveNeighboursByColor = aliveNeighboursByColor.map((colorSum, colorIdx) => vectorsToCheck
        // translate to point [j, i]
        .map(([x, y]) => ([x + j, y + i]))
        // filter out points out of bounds
        .filter(validCoordinates)
        // sum alive neighbours
        .reduce(
            (value, [x, y]) => (value + oldPixels[y][x][colorIdx]),
            colorSum,
        ));

    // Should the central cells be alive? (color index iterates over colors)
    return aliveNeighboursByColor.map(
        (colorSum, colorIdx) => classicGoLTricolorRule(colorSum, oldPixels, i, j, colorIdx),
    );
}

/**
 * Function to apply turnOnOrOff on every pixel, to transform old pixels
 * into newer version, in one time step.
 */
function evolve(pixels) {
    const oldPixels = pixels;

    const height = oldPixels.length;
    const width = oldPixels[0].length;

    const newPixels = oldPixels.map(
        (row, i) => row.map(
            (pixel, j) => turnOnOrOffTricolor(i, j, oldPixels, height, width),
        ),
    );

    return newPixels;
}

const state = {
    pixels: randomPixelsTricolor(100, 100),
    interval: null,
    lastI: null,
    lastJ: null,
};

const getters = {
    pixel: (s) => (i, j, col) => s.pixels[i][j][col],
};

const mutations = {
    stepForward(s) {
        s.pixels = evolve(s.pixels);
    },

    setInterval(s, interval) {
        s.interval = interval;
    },

    addCell(s, { i, j }) {
        if (i !== s.lastI || j !== s.lastJ) {
            if (s.pixels[i]) {
                s.pixels[i].splice(j, 1, ([1, 1, 1]));
            }

            s.lastI = i;
            s.lastJ = j;
        }
    },
};

const actions = {
    stepForward({ commit }) {
        commit('stepForward');
    },

    start({ commit, state: s, dispatch }) {
        if (!s.interval) {
            commit('setInterval', setInterval(() => dispatch('stepForward', 100)));
        }
    },

    stop({ commit, state: s }) {
        if (s.interval) {
            clearInterval(s.interval);
            commit('setInterval', null);
        }
    },

    toggleStart({ state: s, dispatch }) {
        if (s.interval) {
            dispatch('stop');
        } else {
            dispatch('start');
        }
    },
};

export default {
    namespaced: true,

    state,
    getters,
    mutations,
    actions,
};
