const vectorsToCheck = [[-1, -1], [-1, 0], [-1, 1],
    [0, -1], [0, 1], [1, -1], [1, 0], [1, 1]];

/**
 * Generate arrays with content generated by gen function.
 */
function makeArray(len, gen) {
    return Array.from(new Array(len), gen);
}

function indexOfMax(arr) {
    if (arr.length === 0) {
        return -1;
    }

    let max = arr[0];
    let maxIndex = 0;

    for (let i = 1; i < arr.length; i += 1) {
        if (arr[i] > max) {
            maxIndex = i;
            max = arr[i];
        }
    }

    return maxIndex;
}

const ZERO_MULTIPLYING_FACTOR = 4;

function nonUniformRandom(random) {
    if (random <= ZERO_MULTIPLYING_FACTOR) {
        return 0;
    }
    return random - (ZERO_MULTIPLYING_FACTOR - 1);
}

/**
 * Generate arrays with random content.
 */
function randomPixelsQuadLife(width, height) {
    return makeArray(height, () => (
        makeArray(width, () => Math.floor(
            nonUniformRandom(Math.random() * (ZERO_MULTIPLYING_FACTOR + 4)),
        ))
    ));
}

function makeValidatorForRange(a, b) {
    return (n) => (a <= n && n <= b);
}

/**
 * @param colorIdx color index
 */
function quadLifeRule(aliveNeighboursByColor, oldPixels, i, j) {
    const centralPoint = oldPixels[i][j];
    /* eslint-disable-next-line no-unused-vars */
    const [first, ...rest] = aliveNeighboursByColor;
    const totalNumberOfAlive = rest.reduce((a, b) => a + b, 0);

    const maxColorIdx = indexOfMax(rest);
    const maxColorQuantity = rest[maxColorIdx];

    // empty cell logic
    if (centralPoint === 0 && (totalNumberOfAlive === 3)
        && maxColorQuantity >= 2) {
        return maxColorIdx + 1;
    }
    if (centralPoint === 0 && totalNumberOfAlive === 3
        // there are 3 groups with num === 1 each
        && rest.filter((number) => number === 1).length === 3) {
        return rest.findIndex((number) => number === 0) + 1;
    }
    if (centralPoint !== 0 && (totalNumberOfAlive === 2 || totalNumberOfAlive === 3)) {
        return centralPoint;
    }
    // if (aliveNeighbours === 3) {
    //     return 1;
    // }
    // if (aliveNeighbours === 2 && oldPixels[i][j][colorIdx] === 1) {
    //     return 1;
    // }
    return 0;
}

/**
 * Basic logic function saying if pixel should be turned on or off.
 */
function turnOnOrOffQuadLife(i, j, oldPixels, height, width) {
    let aliveNeighboursByColor = [0, 0, 0, 0, 0];

    const validXCoordinate = makeValidatorForRange(0, width - 1);
    const validYCoordinate = makeValidatorForRange(0, height - 1);

    const validCoordinates = ([x, y]) => (
        validXCoordinate(x) && validYCoordinate(y)
    );

    // vector way

    aliveNeighboursByColor = aliveNeighboursByColor.map((colorSum, colorIdx) => vectorsToCheck
        // translate to point [j, i]
        .map(([x, y]) => ([x + j, y + i]))
        // filter out points out of bounds
        .filter(validCoordinates)
        // sum alive neighbours
        .reduce(
            (value, [x, y]) => {
                if (oldPixels[y][x] === colorIdx) {
                    return (value + 1);
                }
                return value;
            },
            colorSum,
        ));

    // Should the central cells be alive? (color index iterates over colors)
    return quadLifeRule(aliveNeighboursByColor, oldPixels, i, j);
}

/**
 * Function to apply turnOnOrOff on every pixel, to transform old pixels
 * into newer version, in one time step.
 */
function evolve(pixels) {
    const oldPixels = pixels;

    const height = oldPixels.length;
    const width = oldPixels[0].length;

    const newPixels = oldPixels.map(
        (row, i) => row.map(
            (pixel, j) => turnOnOrOffQuadLife(i, j, oldPixels, height, width),
        ),
    );

    return newPixels;
}

const state = {
    pixels: randomPixelsQuadLife(100, 100),
};

const getters = {
    pixel: (s) => (i, j, col) => s.pixels[i][j][col],
};

const mutations = {
    stepForward(s) {
        /* eslint-disable-next-line no-param-reassign */
        s.pixels = evolve(s.pixels);
    },
};

const actions = {
    stepForward({ commit }) {
        commit('stepForward');
    },
};

export default {
    namespaced: true,

    state,
    getters,
    mutations,
    actions,
};
