export function makeValidatorForRange(a, b) {
    return (n) => (a <= n && n <= b);
}

export const vectorsToCheck = [[-1, -1], [-1, 0], [-1, 1],
    [0, -1], [0, 1], [1, -1], [1, 0], [1, 1]];

/**
 * Generate arrays with content generated by gen function.
 */
export function makeArray(len, gen) {
    return Array.from(new Array(len), gen);
}
